name: Data extract

on:
  schedule:
    - cron: '30 17-22 * * *'

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: cd crawler && npm install && npm start
        env:
          MS_URL: https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalMapa
          APPLICATION_ID: unAFkcaNDeXajurGB7LChj8SgQYS2ptm
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'data'  
          author_name: Arthur Ribeiro
          author_email: devarthurribeiro@gmail.com
          force: false
          message: 'Update reports'
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
