name: Update reports

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - run: cd crawler && npm install && node index.js
        env:
          MS_URL: http://plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js
          OD_URL: https://olhardigital.com.br/site/arquivos/json/covid19.json
      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: 'data'  
          author_name: Arthur Ribeiro
          author_email: devarthurribeiro@gmail.com
          force: false
          message: 'Update reports'
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
