name: Update reports

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd crawler
    - run: npm install
    - run: node index.js
      env:
        MS_URL: http://plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js
        OD_URL=: https://olhardigital.com.br/site/arquivos/json/covid19.json
